#install.packages("KoNLP")
#install.packages("wordcloud")
#install.packages("htmlwidgets")
##install.packages("htmltools")
#install.packages("base64enc")
#install.packages("yaml")
#install.packages("jsonlite")
#install.packages("extrafont")
#install_github("lchiffon/wordcloud2")
#install.packages("webshot")
#install.packages("Rccp")
#install.packages("Sejong")
#install.packages("stringr")
#install.packages("hash")
#install.packages("rJava")
#install.packages("httr")
#install.packages("dplyr")
#install.packages("remotes")
#remotes::install_github('haven-jeon/KoNLP', upgrade = 'never', INSTALL_opts=c('--no-multiarch'))
#Sys.setenv(JAVA_HOME="C:\\Program Files\\Java\\jdk1.8.0_102")
#install.packages("tau")
#install.packages("devtools")
#install.packages("RSelenium")
library(RSelenium)
library(rJava)
library(stringr)
library(jsonlite)
library(dplyr)
library(rvest)
library(httr)
library(stringr)
library(XML)
library(KoNLP)
library(wordcloud)
library(RColorBrewer)
library('reshape2')
library(tidyr)
library(tidytext)
library('tidyverse')
library(wordcloud2)
library(devtools)
library(extrafont)
library(htmltools)
library(base64enc)
library(yaml)
library(jsonlite)
require(devtools)
library(webshot)
library(htmlwidgets)

remdr<- remoteDriver(remoteServerAddr="localhost", port=4445L,browserName="chrome")
remdr$open()

remdr$navigate("https://play.google.com/store/apps/details?id=kr.goodchoice.abouthere&showAllReviews=true")
t <- "¾ß³îÀÚ"
html <- remdr$getPageSource()[[1]]
html <- read_html(html)
a_r <- html %>% html_nodes(".WpDbMd") %>% html_text()
a_r

# a_r  <- gsub("[a-z]", "", a_r)
# a_r  <- gsub("[A-Z]", "", a_r)
# a_r  <- gsub("[[:digit:]]", "", a_r)
# a_r  <- gsub("[[:punct:]]", "", a_r)
a_r
a <- read_lines(file.choose('review.txt')) # ÃßÃâµÈ µ¥ÀÌÆ®¸¦ .txt ÆÄÀÏ·Î ÀúÀå
a
# a  <- gsub("È¯", "È¯ºÒ", a)
# a  <- gsub("¿¹¾àÃë¼Ò", "Ãë¼Ò", a)
# a  <- gsub("Ãë¼Ò", "¿¹¾àÃë¼Ò", a)
# a  <- gsub("¿¹¾àÃë¼ÒÃ³¸®", "¿¹¾àÃë¼Ò", a)
# a  <- gsub("¿¹¾àÃë", "¿¹¾àÃë¼Ò", a)
# a  <- gsub("È¯ºÒºÒ", "È¯ºÒ", a)
# a  <- gsub("°áÁ¦ÇÒ", "°áÁ¦", a)
# a  <- gsub("¿î¿µ¹æ½Ä ¿¬°áÇÏ·Á", "¿î¿µ¹æ½Ä", a)
# a  <- gsub("¿î¿µ¹æ½Ä ¿¬°áÇÏ·Á", "", a)
# a  <- gsub("»¡°£±Û¾¾·Î", "", a)
# a  <- gsub("ÀÌÈÄ", "", a)
# a  <- gsub("¾ê±â", "", a)
# a  <- gsub("¼ö½É", "", a)
# a  <- gsub("»ý°¢", "", a)
# a  <- gsub("´öºÐ´ëÀÀ", "´ëÀÀ", a)
# a  <- gsub("Á¶°Ç", "", a)
# a  <- gsub("¾ð±Þ", "", a)
# a  <- gsub("¼ö½É", "", a)
# a  <- gsub("»õº®", "", a)
# a  <- gsub("ÀÌ¿ëÇÒ", "", a)
# a  <- gsub("¿¬°áÇÏ·Á", "", a)
# a  <- gsub("»ý°¢", "", a)
# a  <- gsub("»ý°¢", "", a)
# a  <- gsub("±ÇÇÑ±òÁö", "", a)
# a  <- gsub("±ÔÁ¤±òÁö", "", a)
# a  <- gsub("°áÁ¦¶§", "°áÁ¦", a)
# a  <- gsub("½Ã°£°è¼Ó", "½Ã°£", a)
# a  <- gsub("¿¹¾àÃë¼Ò¼Ò", "¿¹¾àÃë¼Ò", a)
# a  <- gsub("¿¹¾àÇÑ", "¿¹¾à", a)
# a  <- gsub("¿¹¾àÃë", "¿¹¾àÃë¼Ò", a)
# a  <- gsub("µ¿ÀÏÇÑµ¥", "", a)
# a  <- gsub("¾îÇÃÀÚÃ¼", "¾îÇÃ", a)
# a  <- gsub("ÀüÈ­·®", "ÀüÈ­", a)
# a  <- gsub("È¯ºÒ´É", "È¯ºÒ", a)
# a  <- gsub("Æ¯¼º»ó", "Æ¯¼º", a)
# a  <- gsub("¼±ÅÃÃ¢", "", a)
# a  <- gsub("±ÔÁ¤±òÁö", "", a)
# a  <- gsub("¾²·¹±â¿¹¾à´Ù", "", a)
# a  <- gsub("È¯ºÒ¿¹¾àÃë¼Ò", "¿¹¾àÃë¼Ò", a)
# a  <- gsub("°ü·Ã", "", a)
# a  <- gsub("´äº¯", "´ëÀÀ", a)
# a  <- gsub("Àç¼³Ä¡", "", a)
# a  <- gsub("ÅëÈ­", "¿¬¶ô", a)
# a  <- gsub("¿¹¾àÃë¼ÒµÇ", "¿¹¾àÃë¼Ò", a)
# a  <- gsub("ÇÏ³ª", "", a)
# a  <- gsub("´öºÐ", "", a)
# a  <- gsub("¿î¿µ¹æ½Ä", "¿î¿µ", a)
# a  <- gsub("°æÇè", "", a)
# a  <- gsub("ÄÚµå", "", a)
# a  <- gsub("ÁÖÂ÷ÇÑ", "", a)
# a  <- gsub("¿¹¾à´Ù", "¿¹¾à", a)
# a  <- gsub("»ó´ç¿ø", "»ó´ã¿ø", a)
# a  <- gsub("¿¹¾àÃë", "¿¹¾àÃë¼Ò", a)
# a  <- gsub("±òÁö", "", a)
# a  <- gsub("¾û¸Á", "¹®Á¦", a)
# a  <- gsub("Àß¸ø", "¹®Á¦", a)
# a  <- gsub("¿¹¾àÃë¼ÒÇØÁÖ", "¿¹¾àÃë¼Ò", a)
# a  <- gsub("¸»¾¸", "", a)
# a  <- gsub("¸ñ·Ï", "", a)
# a  <- gsub("¼ö½Ê", "", a)
# a  <- gsub("½Ã½ºÅÛ", "¾îÇÃ", a)
# a  <- gsub("¸ðÅÚ", "¼÷¹Ú½Ã¼³", a)
# a  <- gsub("Ææ¼Ç", "¼÷¹Ú½Ã¼³", a)
# a  <- gsub("¿¹¾àÃë¼Ò¼Ò¼Ò", "¿¹¾àÃë¼Ò", a)
# a  <- gsub("ÆÒ¼Ç", "¼÷¹Ú½Ã¼³", a)
# a  <- gsub("¿¹¾àÃë", "¿¹¾à", a)
# a  <- gsub("¿¹¾àÃë¼Ò¼Ò¼Ò", "¿¹¾àÃë¼Ò", a)
# a <- gsub("À¶Åë¼º", "±ÔÁ¤", a)
# a <- gsub("±ÇÇÑ", "±ÔÁ¤", a)
# a <- gsub("¿¹¾à¼Ò", "¿¹¾àÃë¼Ò", a)
# a <- gsub("\\", "", a)
# a <- gsub("¿¹¾àÃë¼ÒÇÏ°Ô", "¿¹¾àÃë¼Ò", a)
# a <- gsub("¿¹¾àÇß½À´Ï´Ù½Ã°£", "¿¹¾à", a)
# a <- gsub("¾Ë¹Ù»ý", "»ó´ã¿ø", a)
# a <- gsub("¿¬¶ôÁß", "ÀüÈ­", a)
# a <- gsub("¿¹¾àÃë¼Ò¿¹¾àÃë¼Ò", "¿¹¾àÃë¼Ò", a)
# a <- gsub("¾Ê¹ÞÀ½", "", a)
# a <- gsub("¾çÇØÇØ´Þ¶ó´Â°Ç¾Æ´Ï", "", a)
# a <- gsub("ÇÚµåÆù", "ÀüÈ­", a)
# a <- gsub("¼÷¹Ú¿¬°á¾Û", "¾îÇÃ", a)
# a <- gsub("Àß¹®Á¦À»", "¹®Á¦", a)
# a <- gsub("°áÁ¦ÇÑ°Å", "°áÁ¦", a)
# a <- gsub("ÀÌ¿ëÇÏ", "ÀÌ¿ë", a)
# a <- gsub("¼º¼ö±â¶§", "¼º¼ö±â", a)
# a <- gsub("¾î·Á¿ï¼öÀÖ´ÂÁ¡", "", a)
# a <- gsub("¿¹¾àÃë¼Ò½ÂÀÎÇØÁÖ", "¿¹¾àÃë¼Ò", a)
# a <- gsub("¿À´Ã³¯Â¥", "³¯Â¥º¯°æ", a)
# a <- gsub("¹®Á¦ÁøÃ¢", "¹®Á¦", a)
# a <- gsub("Ã¼Å©ÀÎÇÒ¼öÀÖ´ÂÇØ´ç½Ã°£¿¹¾àÃë¼Ò¾ÈµÈ´Ù´Â°Ô", "¿¹¾àÃë¼Ò", a)
# a <- gsub("¾Ç¿ïÇØ¼­", "¾ï¿ï", a)
# a <- gsub("µ¿ÀÏ", "", a)
# a <- gsub("¼÷¹Ú¾Û", "¾îÇÃ", a)
# a <- gsub("ÇÁ·Î", "»ó´ã¿ø", a)
# a <- gsub("¾÷µ¥ÀÌÆ®Á»", "¾îÇÃ", a)
# a <- gsub("ÀüÃ¼", "", a)
# a <- gsub("¾È¹Þ°í", "", a)
# a <- gsub("ÀÌ¿ëÀÚ", "°í°´", a)
# a <- gsub("½Ã°£¶§¿ì±â³ªÇÏ°í´ÙÀ½³¯", "³¯Â¥", a)
# a <- gsub("¿¹¾àÃë¼Ò¾È", "¿¹¾àÃë¼Ò", a)
# a <- gsub("¿¹¾àÃë¼ÒÇÒ¸¸ÇÏ¸é", "¿¹¾àÃë¼Ò", a)
# a <- gsub("ÆÇ´ÜÇØ¼­", "´ëÀÀ", a)
# a <- gsub("¿¹¾àÃë¼Ò´ÉÇÏ", "¿¹¾àÃë¼Ò", a)
# a <- gsub("ÀÇ¹®", "ºÒ¸¸", a)
# a <- gsub("Ä«Åå¹®", "Ä«Ä«¿ÀÅå", a)
# a <- gsub("Æí»çÇ×", "ÆíÀÇ»çÇ×", a)
# a <- gsub("ÀÖ´ÙÇÏ´õ¶óµµ", "", a)
# a <- gsub("Àß»ì¾Æº¸½Ê¼î", "ºÒ¸¸", a)
# a <- gsub("¼­ºñ½º»ó´ã¿ø", "»ó´ã¿ø", a)
# a <- gsub("½Ç¸ÁÇØ", "½Ç¸Á", a)
# a <- gsub("¾È»ý±â", "", a)
# a <- gsub("ÀÌµûÀ§", "", a)
# a <- gsub("ÇØ¼­±ò¾Ò´Ù", "", a)
# a <- gsub("È¯ºÒ¹Þ°Ô", "È¯ºÒ", a)
# a <- gsub("ÇÏ¼Ò¿¬", "ºÒ¸¸", a)
# a <- gsub("Â÷ÇÑ", "", a)
# a <- gsub("ÀÔ½ÇÇÏ", "", a)
# a <- gsub("¿ÀÇØÇÒ¸¸ÇÑ", "¿ÀÇØ", a)
# a <- gsub("¾È¾µ°Å¿ä", "", a)
# a <- gsub("Àý´ëºñÃß", "ºÒ¸¸", a)
# a <- gsub("Á¢¼Ó", "", a)
# a <- gsub("ÀÌÀü", "", a)
# a <- gsub("¿¹¾àÃë¼Ò¹öÆ°ÀÌ", "¿¹¾àÃë¼Ò", a)
# a <- gsub("¿¹¾àÃë¼ÒÇÏ·Á", "¿¹¾àÃë¼Ò", a)
# a <- gsub("ÀÌÁ¨", "", a)
# a <- gsub("¿¹¾àÃë¼ÒÇØ¼­", "¿¹¾àÃë¼Ò", a)
# a <- gsub("¿î¿ëµÇ", "¿î¿µ", a)
# a <- gsub("¼¼¿ù¾Æ", "", a)
# a <- gsub("ÂùÁö", "", a)
# a <- gsub("ÇÏ·ç", "", a)
# a <- gsub("½Ã°£µ¿¾È", "", a)
# a <- gsub("¾Ê´Â°Å", "", a)
# a <- gsub("Çàº¹¼¾ÅÍ", "°í°´¼¾ÅÍ", a)
# a <- gsub("È£±¸", "°í°´", a)
# a <- gsub("ÀÌÇØÇÏÁö", "ÀÌÇØ", a)
# a <- gsub("¾ÈÀ½", "", a)
# a <- gsub("¾µ°Í", "", a)
# a <- gsub("¾÷ÁÖ", "»çÀå´Ô", a)
# a <- gsub("¼öÁ¤ÇÏ·Á", "", a)
# a <- gsub("À¯µµ", "", a)
# a <- gsub("ÀÔ½Ç", "¼÷¹Ú½Ã¼³", a)
# a <- gsub("ÅÊÀÌ", "", a)
# a <- gsub("ÇØ¼ÒÇÏ±âÀ§ÇØ", "ÇØ°á", a)
# a <- gsub("¸î»ó´ã¿ø", "»ó´ã¿ø¿ø", a)
# a <- gsub("»ó´ã¿ø¿ø", "»ó´ã¿ø", a)
# a <- gsub("Ä«Ä«¿ÀÅåÅå", "Ä«Ä«¿ÀÅå", a)
# a <- gsub("»ó´ã»ç", "»ó´ã¿ø", a)
# a <- gsub("ÁøÂ¥", "ºÒ¸¸", a)
# a <- gsub("È²´ç", "ºÒ¸¸", a)
# a <- gsub("½Ç¼ö", "ºÒ¸¸", a)
# a <- gsub("¿¹¾àÃë", "¿¹¾àÃë¼Ò", a)
# a <- gsub("¿¹¾àÃë¼Ò¼Ò", "¿¹¾àÃë¼Ò", a)
# a <- gsub("¿¹¾àÃë", "¿¹¾àÃë¼Ò", a)
# a <- gsub("ºÒ¸¸ÇÏ", "ºÒ¸¸", a)
# a <- gsub("¿¬°á", "¿¬¶ô", a)
# a <- gsub("¿¹¾àÃë¼ÒµÇ", "¿¹¾àÃë¼Ò", a)
# a <- gsub("¿¹¾àÃë¼ÒÇØÁÖ", "¿¹¾àÃë¼Ò", a)
# a <- gsub("¼÷¼Ò", "¼÷¹Ú½Ã¼³", a)
# a <- gsub("¼Òºñ", "½Ã°£", a)
# a <- gsub("Ä«Åå", "Ä«Ä«¿ÀÅå", a)
# a <- gsub("³¯Â¥", "³¯Â¥º¯°æ", a)
# a <- gsub("°í°´", "°í°´¼¾ÅÍ", a)
# a <- gsub("°í°´¼¾ÅÍÅÂµµ", "°í°´¼¾ÅÍ", a)
# a <- gsub("³¯Â¥º¯°æº¯°æ", "³¯Â¥º¯°æ", a)
# a <- gsub("¾Û", "¾îÇÃ", a)
# a <- gsub("°Í", "", a)
# a <- gsub("½Ã°£ÀÚ", "½Ã°£", a)
# a <- gsub("°í°´¼¾ÅÍÀÀ´ë", "°í°´¼¾ÅÍ", a)
# a <- gsub("¿¬¶ô¾È", "¿¬¶ô", a)
# a <- gsub("»ç¿ëÀÚ", "°í°´", a)
# a <- gsub("´ëÀÀ", "ÀÀ´ë", a)
# a <- gsub("¹®", "¿¹¾àÃë¼Ò", a)
# a <- gsub("À»", "", a)
# a <- gsub("°Í", "", a)
# a <- gsub("°Å", "", a)
# a <- gsub("ÈÄ", "", a)
# a <- gsub("¿¹¾àÃë¼ÒÁ¦", "¿¹¾àÃë¼Ò", a)
# a <- gsub("¼­ºñ½ºÁ¡°Ë", "¼­ºñ½º", a)
# a <- gsub("»çÀ¯", "ÀÌÀ¯", a)
# a <- gsub("µµº¸Â÷·®¹æ¿¹¾àÃë", "", a)
# a <- gsub("°í°´¼¾ÅÍ¿¹¾àÃë¼Ò", "¿¹¾àÃë¼Ò", a)
# a <- gsub("¼÷¹Ú", "¼÷¹Ú½Ã¼³", a)
# a <- gsub("¼÷¹Ú½Ã¼³½Ã¼³", "¼÷¹Ú½Ã¼³", a)
# a <- gsub("°í°´¼¾ÅÍ¶ó´Â°Ô", "°í°´¼¾ÅÍ", a)
# a <- gsub("°áÁ¦Ã¢", "°áÁ¦", a)
# a <- gsub("¾îÇÃµðÀÚÀÎ", "¾îÇÃ", a)
# a <- gsub("¼÷¹Ú½Ã¼³¶óÇØ¼­", "¼÷¹Ú½Ã¼³", a)
# a <- gsub("¿¹¾àÃë¼Ò°Ú´ÙÇÏ´ÂÁö", "¿¹¾àÃë¼Ò", a)
# a <- gsub("¿¹¾àºÒ¸¸ÇÏ´Â°É", "ºÒ¸¸", a)
# a <- gsub("ºÒ¸¸ÇÑ", "ºÒ¸¸", a)
# a <- gsub("¿¹¾àºÒ¸¸°É", "ºÒ¸¸", a)
# a <- gsub("¿¹¾àºÒ¸¸", "¿¹¾àºÒÆí", a)
# a <- gsub("¿¹¾àÃë¼Ò±¸", "¿¹¾àÃë¼Ò", a)
# a <- gsub("¾îÇÃ¿¹¾àÃë¼Ò", "¿¹¾àÃë¼Ò", a)
# a <- gsub("¿¹¾àÁöºÐ¸¸", "¿¹¾à", a)
# a <- gsub("¿¹¾àÃë¼ÒÇß°Å°í", "¿¹¾àÃë¼Ò", a)
# a <- gsub("¿¹¾àÃë¼ÒÀÇÇÏ¶óÇØ¼­", "¿¹¾àÃë¼Ò", a)
# a <- gsub("¿¹¾àÃë¼ÒÇÏ¸éµÈ´ÙÇØ¼­", "¿¹¾àÃë¼Ò", a)
# a <- gsub("´çÀÏ", "´çÀÏ¿¹¾àÃë¼Ò", a)
# a <- gsub("ÇÑ", "", a)
# a <- gsub("¹ø", "", a)
# a <- gsub("Æí", "", a)
# a <- gsub("¼Ò", "", a)
# a <- gsub("³¯", "", a)
# a <- gsub("¾Õ", "", a)
# a <- gsub("³ª", "", a)
# a <- gsub("ºÐ", "", a)
# a <- gsub("±â", "", a)
# a <- gsub("·Î", "", a)
# a <- gsub("Áö", "", a)
# a <- gsub("½Ã", "", a)
# a <- gsub("¶Ç", "", a)
# a <- gsub("¸é", "", a)
# a <- gsub("¹ß", "", a)
# a <- gsub("µî", "", a)
# a <- gsub("µÚ", "", a)
# a <- gsub("µÑ", "", a)
# a <- gsub("¿¹¾àºÒ", "¿¹¾àºÒÆí", a)
# a <- gsub("Â¥º¯°æ", "³¯Â¥º¯°æ", a)
# a <- gsub("¿¹¾àÃë", "¿¹¾àÃë¼Ò", a)
# a <- gsub("¼÷¹Ú¼³", "¼÷¹Ú½Ã¼³", a)
# a <- gsub("¼÷¹Ú½Ã¼³¿¹¾à", "¿¹¾à", a)
# a <- gsub("º¸¹æ¿¹¾àÃë¼Ò", "¿¹¾àÃë¼Ò", a)
# a <- gsub("»çÀå´ÔÃø¼­", "»çÀå´Ô", a)
# a <- gsub("ÀüÈ­ÇØ¼­", "ÀüÈ­", a)
# a <- gsub("¿¹¾àÃë¼ÒÀÌÇØ", "¿¹¾àÃë¼Ò", a)
# a <- gsub("¼ö", "", a)
# a <- gsub("Àú", "", a)
# a <- gsub("³¡", "", a)
# a <- gsub("¸Â", "", a)
# a <- gsub("½Ã", "", a)
# a <- gsub("°©", "", a)
# a <- gsub("±×¶§", "", a)
# a <- gsub("»õ", "", a)
# a <- gsub("ÀÏ¿äÀÏ¼÷¹Ú½Ã¼³", "¼÷¹Ú½Ã¼³", a)
# a <- gsub("°Ýºñ±³ÇÏ", "°¡°Ýºñ±³", a)
# a <- gsub("¾ó", "", a)
# a <- gsub("¿äÃ»", "", a)
# a <- gsub("Ã¹Â°", "", a)
# a <- gsub("¸ÔÆ¢ÇÏ", "", a)
# a <- gsub("¿¹¾àÇÏ", "¿¹¾à", a)
# a <- gsub("¿¬¶ôÀÌ¾È", "¿¬¶ô", a)
# a <- gsub("Â÷·®ÀÌ¿ë", "ÀÌ¿ë", a)
# a <- gsub("¿¹¾àÃë¼Ò¼Ò", "¿¹¾àÃë¼Ò", a)
# a <- gsub("Áö", "", a)
# a <- gsub("½Ã", "", a)
a <- gsub("°í°´¼¾ÅÍ¼¾ÅÍ", "°í°´¼¾ÅÍ", a)
a
a1 <- SimplePos22(a)
a3 <- a1 %>% melt %>% as_tibble

a3 <- a3 %>% 
  mutate(noun=str_match(value, '([°¡-ÆR]+)/N')[,2]) %>%
  na.omit %>% 
  filter(str_length(noun)>=1) %>% 
  count(noun, sort=TRUE) %>%
  filter(n>=0)

colnames(a3) <- c('´Ü¾î', '°³¼ö')

a3 %>% 
  mutate(noun=str_match(value, '([°¡-ÆR]+)/N')[,2]) %>%
  na.omit %>% 
  filter(str_length(noun)>=2) %>% 
  count(noun, sort=TRUE) %>%
  wordcloud2()

wordcloud2(a3, size=1, col="random-dark", rotateRatio= 0)
wordcloud2(a3, size=1, col="random-light", backgroundColor="black", rotateRatio= 0)

a3 <- as.matrix(a3)
barplot(a3$°³¼ö, names.arg = a3$´Ü¾î)
a3
a3 <- as.data.frame(a3, stringAsFactors = F)
a3 <- a3[1:20,]
a3
barplot(a3$°³¼ö, names.arg = a3$´Ü¾î, col=rainbow(length(a5$´Ü¾î)))
